name: Test on Push
on: [push, pull_request]
jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Setup Tools
        # env:
        #   GO111MODULE: on
        run: |
          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - name: Check out Code
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: go mod download
      - name: Lint
        run: |
          make lint
          # export PATH=$PATH:$(go env GOPATH)/bin
          # golangci-lint run
      - name: Unit Test
        run: make test
      # - name: Integration Test
      #   run: make inte
      #   continue-on-error: true
      - name: Upload coverage to Codecov
        # -U "--proxy http://http-proxy"
        run: bash <(curl -s https://codecov.io/bash)
          -F unittests
          -n codecov-micros
          -f ./build/coverage.txt
          -B "${GITHUB_REF//refs\/heads\//}"
          -T "${GITHUB_REF//refs\/tags\//}"
          -C "${GITHUB_SHA}"
          -Z || echo 'Codecov upload failed'
        env:
          CI: true
          CODECOV_ENV: github-action
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CODECOV_PR: ${{ github.event.after }}
          CODECOV_SHA: ${{ github.sha }}
  fuzzit-regression:
    name: Fuzzit Regression
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Checkout code
        uses: actions/checkout@v1
      - name: fuzz regression job
        run: export PATH="$PATH:$(go env GOPATH)/bin"; ./scripts/fuzz.sh local-regression
  fuzzit-fuzzing:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: Fuzzit Fuzzing
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Checkout code
        uses: actions/checkout@v1
      - name: fuzz continuous job
        run: export PATH="$PATH:$(go env GOPATH)/bin"; ./scripts/fuzz.sh fuzzing
        env:
          FUZZIT_API_KEY: ${{ secrets.FUZZIT_API_KEY }}
